# version: '3.8'

services:
  cpp_service:
    build:
      context: .
      dockerfile: Dockerfile.my_server
    environment:
      - OPENAI_KEY=${OPENAI_KEY}
    ports:
      - "9000:9000"
    networks:
      my_network:
        ipv4_address: 172.100.0.2  # Static IP for cpp_service

    restart: always

  internal_socket:
    build:
      context: .
      dockerfile: Dockerfile.tts_server
    expose:
      - "9002"
    networks:
      my_network:
        ipv4_address: 172.100.0.3  # Static IP for cpp_service
    restart: always

  nextjs_static:
    build:
      context: .
      dockerfile: Dockerfile.nextjs  # Ensure it points to the correct Dockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx  # Mounts logs to the host machine
    environment:
      - NEXT_PUBLIC_SYSTEM_PROMPT
      - NEXT_PUBLIC_OPENAI_API_KEY
    ports:
      - "9001:80"
    depends_on:
      - cpp_service
    restart: always


networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.100.0.0/16"  # Custom subnet
